# Generated by Django 6.0.4 on 2026-05-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_free',
        ),
    ]
