# Generated by Django 6.0.4 on 2026-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
