# Generated by Django 6.0.4 on 2026-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_feature_table_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='feature',
            field=models.ManyToManyField(blank=True, to='table.feature'),
        ),
    ]
