# Generated by Django 6.0.4 on 2026-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='table_image/')),
                ('seats', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
