# Generated by Django 6.0.4 on 2026-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('table', '0005_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites_tables',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='table.Favorites', to='table.table'),
        ),
    ]
